**Remarque générale sur les devoirs à rendre :** merci de bien vouloir renommer le fichier que vous soumettez sur Educnet sous la forme `grI_devJ_nom_prenom.ipynb` où `I` désigne votre numéro de groupe et `J` le numéro du devoir.

## Devoir 1

- Lire les notes de cours jusqu'à la page 32.

- Faire l'exercice 2.15 et le soumettre sur [Educnet](https://educnet.enpc.fr/course/view.php?id=1776).

  **Date limite de remise** : jeudi 20 avril 2023 à 23h59.

## Devoir 2

- Faire les deux exercices numériques du notebook [`3_integration.ipynb`](notebooks/3_integration.ipynb) et soumettre ce dernier sur [Educnet](https://educnet.enpc.fr/course/view.php?id=1776).

  *Attention : il n’est pas demandé de faire ni de rédiger les démonstrations de l’exercice théorique en début de notebook mais il est utile de le lire car les exercices numériques s’appuient sur des résultats exposés dans cet exercice.*

  **Date limite de remise** : lundi 1er mai 2023 à 23h59.

## Devoir 3

- Faire tous les exercices du notebook [`4_systemes_lineaires_gradients_conjugues.ipynb`](notebooks/4_systemes_lineaires_gradients_conjugues.ipynb) et soumettre ce dernier sur [Educnet](https://educnet.enpc.fr/course/view.php?id=1776).

  **Date limite de remise** : lundi 15 mai 2023 à 23h59.

## Devoir 4

- Terminer le notebook [`5_valeurs_propres.ipynb`](notebooks/5_valeurs_propres.ipynb) et soumettre ce dernier sur [Educnet](https://educnet.enpc.fr/course/view.php?id=1776).

  **Date limite de remise** : lundi 29 mai 2023 à 23h59.

## Devoir 5

- Terminer le notebook [`6_nonlinear_autodiff.ipynb`](notebooks/6_nonlinear_autodiff.ipynb) et soumettre ce dernier sur [Educnet](https://educnet.enpc.fr/course/view.php?id=1776).

  **Date limite de remise** : lundi 5 juin 2023 à 23h59.
