# Liens utiles

## Installation de `Julia`

`Julia` peut être installé par l'une des deux options suivantes (la seconde étant préférable car elle devrait devenir à terme la solution officielle)

- Installation classique depuis le site : <https://julialang.org/downloads>

- Installation par le biais de *juliaup* <https://github.com/JuliaLang/juliaup>, par exemple [ici](https://www.microsoft.com/store/apps/9NJNWW8PVKMN) pour Windows.

  **Note:** sans accès au Windows Store (par exemple restrictions dues à une politique informatique d'entreprise) il est possible de trouver une solution alternative d'installation de *juliaup* [ici](https://discourse.julialang.org/t/looking-for-feedback-from-users-that-currently-cant-install-juliaup-from-the-windows-store/85507) qui se résume à

    1. Télécharger le fichier [Julia.appinstaller](https://install.julialang.org/Julia.appinstaller)

    1. Exécuter le code suivant sous Powershell

       ```shell
       PS [path] Add-AppxPackage -AppInstallerFile Julia.appinstaller
       ```

## Vidéos

Quelques vidéos utiles pour se familiariser avec le langage `Julia`

- [Intro to Julia tutorial (version 1.0) by Jane Herriman](https://youtu.be/8h8rQyEpiZA)
  Introduction assez complète de la syntaxe de base et quelques éléments avancés.

- [The Unreasonable Effectiveness of Multiple Dispatch](https://www.youtube.com/watch?v=kc9HwsxE1OY)
  Plus de détails sur un atout majeur du langage : le "multiple dispatch".

## Bibliothèques utiles pour le cours

- [Documentation générale de `Julia`](https://docs.julialang.org/en/v1/)

- [`Polynomials.jl`](https://github.com/JuliaMath/Polynomials.jl)

- [`Interpolations.jl`](https://github.com/JuliaMath/Interpolations.jl)

