# Notebooks

## Semaine 1

- [Introduction au langage Julia](notebooks/intro_julia.ipynb)

Devoir à remettre sur [Educnet](https://educnet.enpc.fr/mod/assign/view.php?id=65028) au plus tard le **jeudi 25 avril 2024, 23:59**.

## Semaine 2

- [Interpolation, approximation et intégration](notebooks/interpolation.ipynb)

Devoir à remettre sur [Educnet](https://educnet.enpc.fr/mod/assign/view.php?id=65147) au plus tard le **jeudi 2 mai 2024, 23:59**.

## Semaine 3

- [Systèmes linéaires](notebooks/linear.ipynb)

**Correction**: Dans l'énoncé de l'exercice 3.4,

- remplacer `e_k` par `r_k`

- remplacer A - ωI par I - ωA

Devoir à remettre sur [Educnet](https://educnet.enpc.fr/mod/assign/view.php?id=65638) au plus tard le **jeudi 16 mai 2024, 23:59**.

## Semaine 4

- [Problèmes aux valeurs propres](notebooks/eigen.ipynb)

Devoir à remettre sur [Educnet](https://educnet.enpc.fr/mod/assign/view.php?id=65760) au plus tard le **jeudi 23 mai 2024, 23:59**.

## Semaine 5

- [Équations non linéaires](notebooks/nonlinear.ipynb)

Devoir à remettre sur [Educnet](https://educnet.enpc.fr/mod/assign/view.php?id=65812) au plus tard le **jeudi 30 mai 2024, 23:59**.

## Semaine 6

- [Équations différentielles ordinaires](notebooks/odes.ipynb)

Ce notebook n'est pas à remettre.
